export const ADD_FIX_REQUEST = 'ADD_FIX_REQUEST'
export const REMOVE_FIX_REQUEST = 'REMOVE_FIX_REQUEST'

export const ADD_RETURN_REQUEST = 'ADD_RETURN_REQUEST'
export const REMOVE_RETURN_REQUEST = 'REMOVE_RETURN_REQUEST'

export const OPEN = 'open'
export const CLOSE = 'close'

//auth.js
export const LOG_IN = 'LOG_IN'
export const LOG_OUT = 'LOG_OUT'
export const SIGN_IN = 'SIGN_IN'

//Get User Infor
//getInfo.js

export const GET_INFO = 'GET_INFO'

export const GET_DASHBOARD = 'GET_DASHBOARD'
export const EDIT_DASHBOARD = 'EDIT_DASHBOARD'
export const DELETE_DASHBOARD = 'DELETE_DASHBOARD'

export const GET_ADMIN_ACCOUNT = 'GET_ADMIN_ACCOUNT'
export const EDIT_ADMIN_ACCOUNT = 'EDIT_ADMIN_ACCOUNT'

export const GET_ADMIN_INFO = 'GET_ADMIN_INFO'
export const EDIT_ADMIN_INFO = 'EDIT_ADMIN_INFO'

export const GET_STUDENT_ACCOUNT = 'GET_STUDENT_ACCOUNT'
export const EDIT_STUDENT_ACCOUNT = 'EDIT_STUDENT_ACCOUNT'

export const GET_STUDENT_INFO = 'GET_STUDENT_INFO'
export const EDIT_STUDENT_INFO = 'EDIT_STUDENT_INF'

export const ADMIN_SIGN_IN = 'ADMIN_SIGN_IN'
export const ADMIN_SIGN_OUT = 'ADMIN_SIGN_OUT'
export const ADMIN_EDIT_ACCOUNT = 'ADMIN_EDIT_ACCOUNT'

export const STUDENT_SIGN_IN = 'STUDENT_SIGN_IN'
export const STUDENT_SIGN_OUT = 'STUDENT_SIGN_OUT'
export const STUDENT_EDIT_ACCOUNT = 'STUDENT_EDIT_ACCOUNT'


export const ADMIN_SIGN_UP_ADMIN = 'ADMIN_SIGN_UP_ADMIN'
export const ADMIN_SIGN_UP_STUDENT = 'ADMIN_SIGN_UP_STUDENT'

export const ADMIN_FORGOT_ACCOUNT = 'ADMIN_FORGOT_ACCOUNT'
export const STUDENT_FORGOT_ACCOUNT = 'STUDENT_FORGOT_ACCOUNT'

export const STUDENT_SEE_DATA = 'STUDENT_SEE_DATA'

export const STUDENT_SEE_RESIDENT = 'STUDENT_SEE_RESIDENT'
export const STUDENT_SEE_BILLS = 'STUDENT_SEE_BILLS'
export const STUDENT_SEE_NOTIFICATIONS = 'STUDENT_SEE_NOTIFICATIONS'

export const STUDENT_REQUEST_FIX = 'STUDENT_REQUEST_FIX'
export const STUDENT_REQUEST_RETURN = 'STUDENT_REQUEST_RETURN'

export const STUDENT_GET_FIX_REQUEST = 'STUDENT_GET_FIX_REQUEST'
export const STUDENT_GET_RETURN_REQUEST = 'STUDENT_GET_RETURN_REQUEST'

export const ADMIN_SEE_DATA = 'ADMIN_SEE_DATA'
export const ADMIN_SEE_NOTIFICATION = 'ADMIN_SEE_NOTIFICATION'

export const SET_SNACK = 'SET_SNACK'

export const SET_LINEAR = 'SET_LINEAR'